### ISSUE TITLE
origem do csv

### ISSUE THREAD

**Issue by felipebossolani** [BrunoMioto/setorial_stocks_B3#1]
Fala Bruno, tudo bem?

Estou fazendo um estudo/trabalho dos setores da B3. E vi que no site da bolsa temos esse link: http://www.b3.com.br/pt_br/produtos-e-servicos/negociacao/renda-variavel/acoes/consultas/classificacao-setorial/ com um arquivo excel.
Para chegar nesse CSV vc fez um parse de autoria ou o CSV tbm existem em algum outro local.

Forte abraço e obrigado por contribuir com a comunidade.

**Comment by brunomioto** [comment]
Olá Felipe, fico feliz que tenha chegado até meu trabalho.

Eu baixei a planilha da B3 (bem que eles poderiam disponibilizar esses dados em formato csv/aberto...) e editei com o R.

Precisei retirar as vírgulas por causa do csv, por isso tem "e" repetido ali nas petrolíferas e tal.

Fique à vontade para utilizar. A planilha tem os dados atualizados até dia 05/08 se não me falhe a memória

**Comment by felipebossolani** [comment]
Boa, obrigado pelo reply. Vou utilizar sim. Forte abraço,
